spring.application.name=demo
#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/eventhive_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=eventhive
spring.datasource.password=project
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecteventhive@gmail.com
spring.mail.password=tlmq eucv dbxz hutu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#default server port 8080
#server.port=9090